services:
  analysis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rimel-analysis
    volumes:
      - ./:/app
      - ./3-activite-contributeurs/outputs:/outputs
    working_dir: /app
    command: bash -c "echo 'Container ready'"
