# docker-compose.yml
version: '3'
services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-server
    ports:
      - "9000:9000"
    networks:
      - sonar-net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

networks:
  sonar-net:
    driver: bridge